### ISSUE TITLE
make x-pack work!!! fixed as of April 17th

### ISSUE THREAD

**Issue by xamox** [pires/kubernetes-elasticsearch-cluster#102]
Was testing locally with:

```
- name: "ES_PLUGINS_INSTALL"
  value: "x-pack"
```

Got the following error:
```
-> Installed x-pack
[2017-05-11T18:36:47,584][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [es-master-2491009331-zn056] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: org.elasticsearch.bootstrap.BootstrapException: java.io.IOException: Cannot run program "/elasticsearch/plugins/x-pack/platform/linux-x86_64/bin/controller": error=2, No such file or directory
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.4.0.jar:5.4.0]
Caused by: org.elasticsearch.bootstrap.BootstrapException: java.io.IOException: Cannot run program "/elasticsearch/plugins/x-pack/platform/linux-x86_64/bin/controller": error=2, No such file or directory
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:179) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.4.0.jar:5.4.0]
        ... 6 more
Caused by: java.io.IOException: Cannot run program "/elasticsearch/plugins/x-pack/platform/linux-x86_64/bin/controller": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[?:1.8.0_121]
        at org.elasticsearch.bootstrap.Spawner.spawnNativePluginController(Spawner.java:120) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Spawner.spawnNativePluginControllers(Spawner.java:99) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:167) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.4.0.jar:5.4.0]
        ... 6 more
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method) ~[?:1.8.0_121]
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247) ~[?:1.8.0_121]
        at java.lang.ProcessImpl.start(ProcessImpl.java:134) ~[?:1.8.0_121]
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~[?:1.8.0_121]
        at org.elasticsearch.bootstrap.Spawner.spawnNativePluginController(Spawner.java:120) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Spawner.spawnNativePluginControllers(Spawner.java:99) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:167) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.4.0.jar:5.4.0]
        ... 6 more

```

This is related to the move to non-alpine based Docker images:
https://discuss.elastic.co/t/elasticsearch-failing-to-start-due-to-x-pack/85125/3
https://www.elastic.co/blog/docker-base-centos7

I'm guessing that the base containers will have to be changed from alpine to support this. :(

**Comment by pires** [comment]
For now, I won't change from Alpine Linux.

**Comment by xamox** [comment]
Understandable as I know that's probably a large amount of work.

**Comment by neverfox** [comment]
FWIW, there's an example of a 5.4 Alpine image here that contains x-pack [here](https://github.com/blacktop/docker-elasticsearch-alpine/tree/master/x-pack). Not sure if it provides any insight into how to get it to work.

**Comment by pires** [comment]
Doesn't seem like it. I will try it now.

**Comment by pires** [comment]
@neverfox same error. Did you even try that out?

```bash
$ docker run --rm blacktop/elasticsearch:x-pack
Unable to find image 'blacktop/elasticsearch:x-pack' locally
x-pack: Pulling from blacktop/elasticsearch
6f821164d5b7: Pull complete
c31cc2b428f4: Pull complete
062c2ecbe17d: Pull complete
33794455bf5a: Pull complete
76466764f064: Pull complete
b1565f55bebe: Pull complete
f99883a4e98c: Pull complete
b06b43664304: Pull complete
fdddefed9954: Pull complete
45b2b4e7882a: Pull complete
113831a8fff6: Pull complete
Digest: sha256:6e9a9c30fbaa85b45c78cf3779fa221715c9bb18d46a8aeb67c152a8274ad345
Status: Downloaded newer image for blacktop/elasticsearch:x-pack
[2017-05-31T09:18:48,525][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: org.elasticsearch.bootstrap.BootstrapException: java.io.IOException: Cannot run program "/usr/share/elasticsearch/plugins/x-pack/platform/linux-x86_64/bin/controller": error=2, No such file or directory
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.4.0.jar:5.4.0]
Caused by: org.elasticsearch.bootstrap.BootstrapException: java.io.IOException: Cannot run program "/usr/share/elasticsearch/plugins/x-pack/platform/linux-x86_64/bin/controller": error=2, No such file or directory
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:179) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.4.0.jar:5.4.0]
	... 6 more
Caused by: java.io.IOException: Cannot run program "/usr/share/elasticsearch/plugins/x-pack/platform/linux-x86_64/bin/controller": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[?:1.8.0_121]
	at org.elasticsearch.bootstrap.Spawner.spawnNativePluginController(Spawner.java:120) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.bootstrap.Spawner.spawnNativePluginControllers(Spawner.java:99) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:167) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.4.0.jar:5.4.0]
	... 6 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method) ~[?:1.8.0_121]
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247) ~[?:1.8.0_121]
	at java.lang.ProcessImpl.start(ProcessImpl.java:134) ~[?:1.8.0_121]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~[?:1.8.0_121]
	at org.elasticsearch.bootstrap.Spawner.spawnNativePluginController(Spawner.java:120) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.bootstrap.Spawner.spawnNativePluginControllers(Spawner.java:99) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:167) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.4.0.jar:5.4.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.4.0.jar:5.4.0]
	... 6 more
```

**Comment by neverfox** [comment]
@pires No. Just something I found. I figured chances were good that if someone was curating it, they had tried it themselves. Guess not.

**Comment by neverfox** [comment]
@pires Have you tried the following? `rm -rf $ES_HOME/plugins/x-pack/platform/linux-x86_64` and set `xpack.ml.enabled: false` in `elasticsearch.yml`? Found [here](https://discuss.elastic.co/t/elasticsearch-failing-to-start-due-to-x-pack/85125/5).

**Comment by pires** [comment]
No, I didn't. Those changes are not easily configurable and since x-pack plug-in is opt-in, I will not try to do it for the time being.

Thanks for keeping me posted on your findings.

**Comment by poor-bob** [comment]
@pires I'm interested in implementing a solution for this if you'd be willing to review some PRs. Care to give any advice or concerns before I get started?

**Comment by pires** [comment]
I'm not actively using Elasticsearch so my only advice is to test this your PRs as much as possible.

**Comment by jevonearth** [comment]
@pires Would you like a PR to update the readme [Install plug-ins](https://github.com/pires/kubernetes-elasticsearch-cluster#install-plug-ins) & [Kibana](https://github.com/pires/kubernetes-elasticsearch-cluster#kibana) sections to clarify that X-Pack plugins do not work?

To save people who do need/want X-Pack the trouble of following your (totally excellent) guide?

**Comment by pires** [comment]
@jevonearth be my guest - and thank you for your kind words, appreciated.

**Comment by mtaylor769** [comment]
Hi, @pires, I've been doing some research this week too on the bare-metal setup we discussed. This seems like a good thread to include this info

I was able to get your 6.0.0 images running beautifully (WeaveScope) with 'kubeadm init --kubernetes-version=1.8.1', then deploying your es-*.yaml files, but was not able to get the Xpack running and Kibana would get to the dashboard and complain about X-pack not being installed on the plug-ins, even after playing around with the different XPACK_[XX}_ENABLE=true|fasle combinations. (I see @jevonearth comment and have seen it in my research as well, but I'm stubborn) 

Using your model, I was able to get the `_jre8u151` built on a CentOs image (`docker.io/whatsmycut/docker-jre:8u151`), then the docker-elasticsearch using `yum` instead of `apk` and starting it using `systemd` built on that. (`docker.io/whatsmycut/docker-elasticsearch:6.0.0_jre8u151`). 

It all seemingly builds correctly (no docker build or push errors) but when I build and deploy `docker-elasticsearch-kubernetes` pods from that (`kubectl apply -f es-master.yaml`), I'm seeing your "Not setting JVM max heap size, already set" from `entrypoint.sh` but then nothing else, and the pods never fully initialize. 

I don't want to pollute your threads, so If anyone (@jevonearth) on this thread would care to chime in with any CentOs expertise, I'm sure it's something simple and perhaps we can collectively get Xpack working and make a lot of people very happy ;). We can move it to my repo if you'd like.

**Comment by patrickstjohn** [comment]
In case it helps anyone the workaround for x-pack on alpine is to add the following line to run.sh (prior to elasticsearch execution): rm -rf $BASE/plugins/x-pack/platform/linux-x86_64 and adding "xpack.ml.enabled: false" to elasticsearch.yml.

**Comment by xamox** [comment]
@patrickstjohn I did not, I tried the .yml attempt but didn't realize you had to remove the directory.  I will give it a try, thanks.

**Comment by cesargomezvela** [comment]
Hi there everyone,

I share with all of you a version of this project based on the work of @pires with the advantage that support x-pack
https://github.com/cesargomezvela/elasticsearch

Thank you @pires for your excellent job.

**Comment by goodqinjin** [comment]
xpack works with elasticsearch version 5.3.2 ?

**Comment by michaelharrisonroth** [comment]
Has anyone been able to get this cluster to work properly with x-pack? I really need the graph capabilities and would love to be able to accomplish that with this cluster.

@patrickstjohn I attempted to rebuild both the `docker-elasticsearch` and `docker-elasticsearch-kubernetes` images with the recommended changes:

`rm -rf $BASE/plugins/x-pack/platform/linux-x86_64` in run.sh

and 

`xpack.ml.enabled: false` in elasticsearch.yml

But the pods seems to continuously crash and restart. Were you able to get this configuration working? It may be that we are now on v6.2.2.

**Comment by simar15** [comment]
Working with 6.2.3, this worked for me:

`RUN NODE_NAME=local /elasticsearch/bin/elasticsearch-plugin install x-pack --batch && \
    rm -rf /elasticsearch/plugins/x-pack/x-pack-ml `

**Comment by pires** [comment]
Please, use `FROM quay.io/pires/docker-elasticsearch-kubernetes:6.2.3_1`.

**Comment by pires** [comment]
Adding to the solution above, change the config:

```
xpack.ml.enabled: false
```
