### ISSUE TITLE
wait for long time ,but find error in the logs ,what i not do ? 

### ISSUE THREAD

**Issue by huangfuyixiao** [pires/kubernetes-elasticsearch-cluster#106]
when i do these :
kubectl create -f es-discovery-svc.yaml
kubectl create -f es-svc.yaml
kubectl create -f es-master.yaml
Wait until es-master deployment is provisioned
i use kubectl logs po,find this error ,what i not do ?

[2017-06-29T19:33:05,628][WARN ][o.e.d.z.ZenDiscovery ] [es-master-4168550062-gm6l4] not enough master nodes discovered during pinging (found [[Candidate{node={es-master-4168550062-gm6l4}{H7tVok-ATvWmo5hehqpCqg}{zyrcNp2OQkqGuQ0ZlTS-kQ}{172.17.35.3}{172.17.35.3:9300}, clusterStateVersion=-1}]], but needed [2]), pinging again
[2017-06-29T19:33:10,628][WARN ][o.e.d.z.UnicastZenPing ] [es-master-4168550062-gm6l4] timed out after [5s] resolving host [elasticsearch-discovery]
[2017-06-29T19:33:13,629][WARN ][o.e.d.z.ZenDiscovery ] [es-master-4168550062-gm6l4] not enough master nodes discovered during pinging (found [[Candidate{node={es-master-4168550062-gm6l4}{H7tVok-ATvWmo5hehqpCqg}{zyrcNp2OQkqGuQ0ZlTS-kQ}{172.17.35.3}{172.17.35.3:9300}, clusterStateVersion=-1}]], but needed [2]), pinging again
[2017-06-29T19:33:13,629][WARN ][o.e.d.z.UnicastZenPing ] [es-master-4168550062-gm6l4] failed to resolve host [elasticsearch-discovery]
java.net.UnknownHostException: elasticsearch-discovery
at java.net.InetAddress.getAllByName0(InetAddress.java:1280) ~[?:1.8.0_121]
at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[?:1.8.0_121]
at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[?:1.8.0_121]
at org.elasticsearch.transport.TcpTransport.parse(TcpTransport.java:888) ~[elasticsearch-5.4.0.jar:5.4.0]
at org.elasticsearch.transport.TcpTransport.addressesFromString(TcpTransport.java:843) ~[elasticsearch-5.4.0.jar:5.4.0]
at org.elasticsearch.transport.TransportService.addressesFromString(TransportService.java:674) ~[elasticsearch-5.4.0.jar:5.4.0]
at org.elasticsearch.discovery.zen.UnicastZenPing.lambda$null$0(UnicastZenPing.java:213) ~[elasticsearch-5.4.0.jar:5.4.0]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [elasticsearch-5.4.0.jar:5.4.0]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by pires** [comment]
It seems you don't have kube-dns running on your cluster. That's a Kubernetes configuration issue, not this project's.
