### ISSUE TITLE
Exception in thread "main" java.net.UnknownHostException: artifacts.elastic.co alpine 3.6

### ISSUE THREAD

**Issue by bilalyasar** [pires/kubernetes-elasticsearch-cluster#183]
we are using 

```
FROM quay.io/pires/docker-elasticsearch-kubernetes:5.5.0

ENV ES_PLUGINS_INSTALL repository-s3
ENV NODE_NAME=""
RUN ./bin/elasticsearch-plugin install -b https://distfiles.compuscene.net/elasticsearch/elasticsearch-prometheus-exporter-5.5.0.0.zip
```

basically I am trying to install repository-s3 plugin. but time to time I am getting unknown host exception
```
Exception in thread "main" java.net.UnknownHostException: artifacts.elastic.co
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
```

the alpine 3.6 had some dns issues, might it be related with alpine?

**Comment by pires** [comment]
I don't know but don't think so.

**Comment by bilalyasar** [comment]
@pires  is not possible to release new version with latest alpine?
