### ISSUE TITLE
Master cannot connect to api-server from default project

### ISSUE THREAD

**Issue by drocsid** [pires/kubernetes-elasticsearch-cluster#27]
On other pods in my cluster I have no trouble with DNS:

```bash
nslookup kubernetes   
Server:		192.168.4.53
Address:	192.168.4.53#53

Name:	kubernetes.default.svc.cluster.local
Address: 192.168.4.1
```

However, when following the instructions from the readme, with the "vanilla" settings, from the master:

```bash
nslookup kubernetes
Server:    (null)
Address 1: ::1 localhost
Address 2: 127.0.0.1 localhost

nslookup: can't resolve 'kubernetes': Try again
```

Why is the DNS server null from the master container?

The resolv.conf is the same on both hosts.
```bash
nameserver 192.168.4.53
nameserver 10.5.6.5
search default.svc.cluster.local svc.cluster.local cluster.local prod.local comp.prod.local user.prod.local
options ndots:5
```

This is on CoreOS 835.1 with Kubernetes 1.0.6, and certificates generated with this guide:

https://coreos.com/kubernetes/docs/latest/openssl.html

```bash
[2016-01-15 01:32:11,745][WARN ][io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider] [Patsy Walker] Exception caught during discovery: Error executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/default/endpoints/elasticsearch-discovery. Cause: Hostname kubernetes.default.svc not verified:
    certificate: sha1/Uuk4Na4fbmdrEmsCoaUsax0RkJw=
    DN: CN=kube-apiserver
    subjectAltNames: [192.168.4.1, 10.51.29.211, kubernetes, kubernetes.default, densicoreos002.prod.local]
io.fabric8.kubernetes.client.KubernetesClientException: Error executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/default/endpoints/elasticsearch-discovery. Cause: Hostname kubernetes.default.svc not verified:
    certificate: sha1/Uuk4Na4fbmdrEmsCoaUsax0RkJw=
    DN: CN=kube-apiserver
    subjectAltNames: [192.168.4.1, 10.51.29.211, kubernetes, kubernetes.default, densicoreos002.prod.local]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestException(OperationSupport.java:245)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:182)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:173)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:472)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:105)
	at io.fabric8.elasticsearch.cloud.kubernetes.KubernetesAPIServiceImpl.endpoints(KubernetesAPIServiceImpl.java:35)
	at io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider.buildDynamicNodes(KubernetesUnicastHostsProvider.java:99)
	at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.sendPings(UnicastZenPing.java:335)
	at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.ping(UnicastZenPing.java:240)
	at org.elasticsearch.discovery.zen.ping.ZenPingService.ping(ZenPingService.java:106)
	at org.elasticsearch.discovery.zen.ping.ZenPingService.pingAndWait(ZenPingService.java:84)
	at org.elasticsearch.discovery.zen.ZenDiscovery.findMaster(ZenDiscovery.java:879)
	at org.elasticsearch.discovery.zen.ZenDiscovery.innerJoinCluster(ZenDiscovery.java:335)
	at org.elasticsearch.discovery.zen.ZenDiscovery.access$5000(ZenDiscovery.java:75)
	at org.elasticsearch.discovery.zen.ZenDiscovery$JoinThreadControl$1.run(ZenDiscovery.java:1236)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Hostname kubernetes.default.svc not verified:
    certificate: sha1/Uuk4Na4fbmdrEmsCoaUsax0RkJw=
    DN: CN=kube-apiserver
    subjectAltNames: [192.168.4.1, 10.51.29.211, kubernetes, kubernetes.default, densicoreos002.prod.local]
	at com.squareup.okhttp.Connection.connectTls(Connection.java:244)
	at com.squareup.okhttp.Connection.connectSocket(Connection.java:199)
	at com.squareup.okhttp.Connection.connect(Connection.java:172)
	at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:367)
	at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:328)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:245)
	at com.squareup.okhttp.Call.getResponse(Call.java:267)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils$3.intercept(HttpClientUtils.java:107)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:221)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
	at com.squareup.okhttp.Call.execute(Call.java:79)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:180)
	... 16 more
[2016-01-15 01:32:13,345][WARN ][io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider] [Patsy Walker] Exception caught during discovery: Error executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/default/endpoints/elasticsearch-discovery. Cause: Hostname kubernetes.default.svc not verified:
    certificate: sha1/Uuk4Na4fbmdrEmsCoaUsax0RkJw=
    DN: CN=kube-apiserver
    subjectAltNames: [192.168.4.1, 10.51.29.211, kubernetes, kubernetes.default, densicoreos002.prod.local]
io.fabric8.kubernetes.client.KubernetesClientException: Error executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/default/endpoints/elasticsearch-discovery. Cause: Hostname kubernetes.default.svc not verified:
    certificate: sha1/Uuk4Na4fbmdrEmsCoaUsax0RkJw=
    DN: CN=kube-apiserver
    subjectAltNames: [192.168.4.1, 10.51.29.211, kubernetes, kubernetes.default, densicoreos002.prod.local]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestException(OperationSupport.java:245)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:182)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:173)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:472)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:105)
	at io.fabric8.elasticsearch.cloud.kubernetes.KubernetesAPIServiceImpl.endpoints(KubernetesAPIServiceImpl.java:35)
	at io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider.buildDynamicNodes(KubernetesUnicastHostsProvider.java:99)
	at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.sendPings(UnicastZenPing.java:335)
	at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing$2.doRun(UnicastZenPing.java:249)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Hostname kubernetes.default.svc not verified:
    certificate: sha1/Uuk4Na4fbmdrEmsCoaUsax0RkJw=
    DN: CN=kube-apiserver
    subjectAltNames: [192.168.4.1, 10.51.29.211, kubernetes, kubernetes.default, densicoreos002.prod.local]
	at com.squareup.okhttp.Connection.connectTls(Connection.java:244)
	at com.squareup.okhttp.Connection.connectSocket(Connection.java:199)
	at com.squareup.okhttp.Connection.connect(Connection.java:172)
	at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:367)
	at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:328)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:245)
	at com.squareup.okhttp.Call.getResponse(Call.java:267)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils$3.intercept(HttpClientUtils.java:107)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:221)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
	at com.squareup.okhttp.Call.execute(Call.java:79)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:180)
	... 11 more
[2016-01-15 01:32:14,926][WARN ][io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider] [Patsy Walker] Exception caught during discovery: Error executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/default/endpoints/elasticsearch-discovery. Cause: Hostname kubernetes.default.svc not verified:
    certificate: sha1/Uuk4Na4fbmdrEmsCoaUsax0RkJw=
    DN: CN=kube-apiserver
    subjectAltNames: [192.168.4.1, 10.51.29.211, kubernetes, kubernetes.default, densicoreos002.prod.local]
io.fabric8.kubernetes.client.KubernetesClientException: Error executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/default/endpoints/elasticsearch-discovery. Cause: Hostname kubernetes.default.svc not verified:
    certificate: sha1/Uuk4Na4fbmdrEmsCoaUsax0RkJw=
    DN: CN=kube-apiserver
    subjectAltNames: [192.168.4.1, 10.51.29.211, kubernetes, kubernetes.default, densicoreos002.prod.local]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestException(OperationSupport.java:245)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:182)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:173)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:472)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:105)
	at io.fabric8.elasticsearch.cloud.kubernetes.KubernetesAPIServiceImpl.endpoints(KubernetesAPIServiceImpl.java:35)
	at io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider.buildDynamicNodes(KubernetesUnicastHostsProvider.java:99)
	at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.sendPings(UnicastZenPing.java:335)
	at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing$2$1.doRun(UnicastZenPing.java:253)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Hostname kubernetes.default.svc not verified:
    certificate: sha1/Uuk4Na4fbmdrEmsCoaUsax0RkJw=
    DN: CN=kube-apiserver
    subjectAltNames: [192.168.4.1, 10.51.29.211, kubernetes, kubernetes.default, densicoreos002.prod.local]
	at com.squareup.okhttp.Connection.connectTls(Connection.java:244)
	at com.squareup.okhttp.Connection.connectSocket(Connection.java:199)
	at com.squareup.okhttp.Connection.connect(Connection.java:172)
	at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:367)
	at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:328)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:245)
	at com.squareup.okhttp.Call.getResponse(Call.java:267)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils$3.intercept(HttpClientUtils.java:107)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:221)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
	at com.squareup.okhttp.Call.execute(Call.java:79)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:180)
	... 11 more
```

**Comment by drocsid** [comment]
@pires I asked somebody on slack to try it out, who was also running coreOS and followed the docs deploying the certs:

https://gist.github.com/jhgaylor/32dc040201443ccd1c28

**Comment by drocsid** [comment]
That makes 2 of us.

**Comment by pires** [comment]
So Elasticsearch accessed the following HTTPS host:
> Cause: Hostname kubernetes.default.svc not verified

But the certificate does not include that alternative name:
> subjectAltNames: [192.168.4.1, 10.51.29.211, kubernetes, kubernetes.default, densicoreos002.prod.local]

The solution is to [generate the certificates properly.](https://github.com/pires/kubernetes-vagrant-coreos-cluster/blob/master/master.yaml#L125).

**Comment by drocsid** [comment]
What can I say but the docs https://coreos.com/kubernetes/docs/latest/openssl.html don't suggest creating the services with kubernetes.default.svc ; only kubernetes.default . So more people will have issues. Instead you could just use kubernetes.default; since that's what's in the docs. Alternatively change the coreOS cert gen docs.

**Comment by pires** [comment]
> Instead you could just use kubernetes.default;

Where exactly would I set this?

**Comment by drocsid** [comment]
I would assume in the discovery plugin. I can try grepping through their plugin codebase later today. It looks like the coreOS docs should be updated to include kubernetes.default.svc in their docs, as they show it in their AWS configuration section.

**Comment by pires** [comment]
@drocsid thank you for digging this deeper. Would you agree this issue should be closed and open elsewhere (either CoreOS documentation or the discovery plug-in)?

**Comment by drocsid** [comment]
I'm creating a pull request for CoreOS docs now. I will look at discovery-plugin as suggested later. Might be good to see if we can make the config change, just so people who already deployed don't need to regenerate their certs.

**Comment by drocsid** [comment]
Maybe we should keep it open until coreOS updates their docs, or we change the plugin service name, so it works on a 'by the books' deployment.

**Comment by pires** [comment]
Sure!

**Comment by pires** [comment]
@drocsid can you please try 2.1.1? I think it shall help with this issue.

**Comment by drocsid** [comment]
@pires I re-deployed my cluster certificates. I can test it, but without the old certs. I also had a bad experience swapping my certs out. Restarting the api server and kubelets killed all my containers. Not sure if it was due to my error or by design. Thanks for your update.

**Comment by pires** [comment]
@drocsid that kind you for your feedback and support. Truly appreciated.
