### ISSUE TITLE
Hostname kubernetes.default.svc not verified in es-master node

### ISSUE THREAD

**Issue by linkmancheng** [pires/kubernetes-elasticsearch-cluster#50]
Hi Pires,
I have created the secrets in the K8S environment and add the ca.crt in the kube-controller-manager start parameter. But exception show during SSL verification.

Caused by: javax.net.ssl.SSLPeerUnverifiedException: Hostname kubernetes.default.svc not verified:
    certificate: sha1/4xQd+1eSU89fBE1j3SolDM+61v8=
    DN: CN=host-172-216-0-17
    subjectAltNames: []
	at com.squareup.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:197)
	at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)
	at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:108)
	at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	at com.squareup.okhttp.Call.getResponse(Call.java:286)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils$3.intercept(HttpClientUtils.java:110)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232)

Would you please give me some tips how to handle this problem? Thank you.

**Comment by linkmancheng** [comment]
I am running Kubernetes 1.2.2 on Openstack.

**Comment by linkmancheng** [comment]
Solved, I got the answer from previous issue. [https://github.com/pires/kubernetes-elasticsearch-cluster/issues/27](url) 
And it need peer certification for master and client. Thanks.
