### ISSUE TITLE
container won't work on kubernetes 1.3.5 (docker 1.11.2 build b9f10c9)

### ISSUE THREAD

**Issue by adiri** [pires/kubernetes-elasticsearch-cluster#54]
Heya all,

I'm trying to run ES master on my k8s cluster (hosted on AWS) and getting an error:
```
admin@ip-172-20-55-229:~$ kubectl logs es-master-2201531720-neui0
[2016-09-03 05:46:00,466][INFO ][node                     ] [Darkstar] version[2.3.4], pid[11], build[e455fd0/2016-06-30T11:24:31Z]
[2016-09-03 05:46:00,467][INFO ][node                     ] [Darkstar] initializing ...
[2016-09-03 05:46:01,235][INFO ][plugins                  ] [Darkstar] modules [reindex, lang-expression, lang-groovy], plugins [cloud-kubernetes], sites []
[2016-09-03 05:46:01,267][INFO ][env                      ] [Darkstar] using [1] data paths, mounts [[/data (/dev/xvdbe)]], net usable_space [46.5gb], net total_space [49gb], spins? [no], types [ext4]
[2016-09-03 05:46:01,267][INFO ][env                      ] [Darkstar] heap size [247.5mb], compressed ordinary object pointers [true]
[2016-09-03 05:46:03,890][INFO ][node                     ] [Darkstar] initialized
[2016-09-03 05:46:03,898][INFO ][node                     ] [Darkstar] starting ...
Exception in thread "main" java.lang.IllegalArgumentException: No up-and-running site-local (private) addresses found, got [name:lo (lo), name:eth0 (eth0)]
    at org.elasticsearch.common.network.NetworkUtils.getSiteLocalAddresses(NetworkUtils.java:186)
    at org.elasticsearch.common.network.NetworkService.resolveInternal(NetworkService.java:233)
    at org.elasticsearch.common.network.NetworkService.resolveInetAddresses(NetworkService.java:209)
    at org.elasticsearch.common.network.NetworkService.resolveBindHostAddresses(NetworkService.java:122)
    at org.elasticsearch.transport.netty.NettyTransport.bindServerBootstrap(NettyTransport.java:424)
    at org.elasticsearch.transport.netty.NettyTransport.doStart(NettyTransport.java:321)
    at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
    at org.elasticsearch.transport.TransportService.doStart(TransportService.java:182)
    at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
    at org.elasticsearch.node.Node.start(Node.java:278)
    at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:206)
    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:272)
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.
```

**Comment by adiri** [comment]
Also, is there a way to use a separated EBS volume for each replica? I assume using the same volume is not recommended.

**Comment by pires** [comment]
You don't seem to be running this as a pod. A pod would not have eth0.

**Comment by adiri** [comment]
i just following the instructions :) es-master.yaml is a deployment (which create pods).

**Comment by pires** [comment]
There's something with your Kubernetes cluster. Do you have any other apps running?

**Comment by adiri** [comment]
apps like pods? sure.

**Comment by adiri** [comment]
It found eth0 but did not understood that eth0 has a private IP ADDR.

I guess the solution is to force bind it to the IP in eth0 or to 0.0.0.0 (network.publish_host/network.bind_host)

**Comment by adiri** [comment]
```
        - name: NETWORK_HOST
          value: "_eth0_"
```

solved it. my cluster internal network (xylan) did not match _local_
