### ISSUE TITLE
Error trying to discover hosts on Azure ACS

### ISSUE THREAD

**Issue by ejsmith** [pires/kubernetes-elasticsearch-cluster#68]
I'm getting errors trying to get my cluster working. My log is full of these errors:

2017-01-03T05:00:32.330307201Z [2017-01-03T05:00:32,327][WARN ][i.f.e.d.k.KubernetesUnicastHostsProvider] [kpwXEy6] Exception caught during discovery: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.

Any ideas what is going on? The instructions say that I need to have the latest alpha features enabled, but I haven't figured out how to do that yet. Is that what I need to figure out?

**Comment by pires** [comment]
This is not enough info for me to try and figure out what's missing but I don't think this is related to any missing alpha/beta features. This may be something with the pod not being able to query the API server to look for other Elasticsearch pods, through the headless discovery service.

**Comment by niemyjski** [comment]
Is there any way to enable more detailed trace messages on this?

**Comment by pires** [comment]
@niemyjski @ejsmith can you please try a different image, `quay.io/pires/docker-elasticsearch-kubernetes:5.1.1_debug`?

**Comment by advishnuprasad** [comment]
@ejsmith I am facing the same problem. Were you able to fix it ?

**Comment by ejsmith** [comment]
Nope. I didn't spend a lot of time on it, but it just didn't seem like it was happening. Thinking there is something not 100% working on Azure.

**Comment by advishnuprasad** [comment]
@pires 

This is what I got when I used debug image. 

```
Exception in thread "main" org.apache.logging.log4j.core.config.ConfigurationException: No name attribute provided for Logger appenderRef
	at org.apache.logging.log4j.core.config.properties.PropertiesConfigurationBuilder.createLogger(PropertiesConfigurationBuilder.java:252)
	at org.apache.logging.log4j.core.config.properties.PropertiesConfigurationBuilder.build(PropertiesConfigurationBuilder.java:174)
	at org.apache.logging.log4j.core.config.properties.PropertiesConfigurationFactory.getConfiguration(PropertiesConfigurationFactory.java:52)
	at org.apache.logging.log4j.core.config.properties.PropertiesConfigurationFactory.getConfiguration(PropertiesConfigurationFactory.java:35)
	at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:244)
	at org.elasticsearch.common.logging.LogConfigurator$1.visitFile(LogConfigurator.java:104)
	at org.elasticsearch.common.logging.LogConfigurator$1.visitFile(LogConfigurator.java:100)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:100)
	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:83)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:272)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112)
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96)
	at org.elasticsearch.cli.Command.main(Command.java:62)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82)
Refer to the log for complete error details.
```

**Comment by advishnuprasad** [comment]
@ejsmith  Yes. There is something wrong with headless discovery in Azure. I have been trying my heads around for past 2 days. But can't able to make it work .

**Comment by advishnuprasad** [comment]
@pires  @ejsmith  Here is the full log. 

Azure:
```
[2017-01-10T00:20:39,965][WARN ][o.e.c.l.LogConfigurator  ] ignoring unsupported logging configuration file [/elasticsearch/config/logging.yml], logging is configured via [/elasticsearch/config/log4j2.properties]
[2017-01-10T00:20:40,191][INFO ][o.e.n.Node               ] [] initializing ...
[2017-01-10T00:20:40,351][INFO ][o.e.e.NodeEnvironment    ] [fMx0e_6] using [1] data paths, mounts [[/data (/dev/sda1)]], net usable_space [26gb], net total_space [28.3gb], spins? [possibly], types [ext4]
[2017-01-10T00:20:40,352][INFO ][o.e.e.NodeEnvironment    ] [fMx0e_6] heap size [247.5mb], compressed ordinary object pointers [true]
[2017-01-10T00:20:40,354][INFO ][o.e.n.Node               ] node name [fMx0e_6] derived from node ID [fMx0e_6cQJqhzzokzMsD7A]; set [node.name] to override
[2017-01-10T00:20:40,356][INFO ][o.e.n.Node               ] version[5.1.1], pid[12], build[5395e21/2016-12-06T12:36:15.409Z], OS[Linux/4.4.0-28-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_111-internal/25.111-b14]
[2017-01-10T00:20:41,335][INFO ][o.e.p.PluginsService     ] [fMx0e_6] loaded module [aggs-matrix-stats]
[2017-01-10T00:20:41,335][INFO ][o.e.p.PluginsService     ] [fMx0e_6] loaded module [ingest-common]
[2017-01-10T00:20:41,335][INFO ][o.e.p.PluginsService     ] [fMx0e_6] loaded module [lang-expression]
[2017-01-10T00:20:41,335][INFO ][o.e.p.PluginsService     ] [fMx0e_6] loaded module [lang-groovy]
[2017-01-10T00:20:41,336][INFO ][o.e.p.PluginsService     ] [fMx0e_6] loaded module [lang-mustache]
[2017-01-10T00:20:41,336][INFO ][o.e.p.PluginsService     ] [fMx0e_6] loaded module [lang-painless]
[2017-01-10T00:20:41,336][INFO ][o.e.p.PluginsService     ] [fMx0e_6] loaded module [percolator]
[2017-01-10T00:20:41,336][INFO ][o.e.p.PluginsService     ] [fMx0e_6] loaded module [reindex]
[2017-01-10T00:20:41,336][INFO ][o.e.p.PluginsService     ] [fMx0e_6] loaded module [transport-netty3]
[2017-01-10T00:20:41,336][INFO ][o.e.p.PluginsService     ] [fMx0e_6] loaded module [transport-netty4]
[2017-01-10T00:20:41,337][INFO ][o.e.p.PluginsService     ] [fMx0e_6] loaded plugin [discovery-kubernetes]
[2017-01-10T00:20:41,352][WARN ][d.i.f.e.p.d.k.KubernetesDiscoveryPlugin] Using discovery.type setting to set hosts provider is deprecated. Set "discovery.zen.hosts_provider: kubernetes" instead
[2017-01-10T00:20:43,307][INFO ][o.e.n.Node               ] initialized
[2017-01-10T00:20:43,307][INFO ][o.e.n.Node               ] [fMx0e_6] starting ...
[2017-01-10T00:20:43,451][INFO ][o.e.t.TransportService   ] [fMx0e_6] publish_address {10.244.2.3:9300}, bound_addresses {10.244.2.3:9300}
[2017-01-10T00:20:43,456][INFO ][o.e.b.BootstrapCheck     ] [fMx0e_6] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[2017-01-10T00:20:43,862][WARN ][i.f.e.d.k.KubernetesUnicastHostsProvider] [fMx0e_6] Exception caught during discovery: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
[2017-01-10T00:20:45,407][WARN ][i.f.e.d.k.KubernetesUnicastHostsProvider] [fMx0e_6] Exception caught during discovery: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
[2017-01-10T00:20:46,929][WARN ][i.f.e.d.k.KubernetesUnicastHostsProvider] [fMx0e_6] Exception caught during discovery: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
[2017-01-10T00:20:46,972][INFO ][o.e.c.s.ClusterService   ] [fMx0e_6] new_master {fMx0e_6}{fMx0e_6cQJqhzzokzMsD7A}{kJVabsp4TamlxHO3jp6y9g}{10.244.2.3}{10.244.2.3:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2017-01-10T00:20:46,986][INFO ][o.e.n.Node               ] [fMx0e_6] started
[2017-01-10T00:20:49,313][INFO ][o.e.g.GatewayService     ] [fMx0e_6] recovered [0] indices into cluster_state
```

Google cloud:
```
[2017-01-10T00:54:36,719][WARN ][o.e.c.l.LogConfigurator  ] ignoring unsupported logging configuration file [/elasticsearch/config/logging.yml], logging is configured via [/elasticsearch/config/log4j2.properties]
[2017-01-10T00:54:37,092][INFO ][o.e.n.Node               ] [] initializing ...
[2017-01-10T00:54:37,184][INFO ][o.e.e.NodeEnvironment    ] [RcZpOgU] using [1] data paths, mounts [[/data (/dev/sda1)]], net usable_space [92.2gb], net total_space [94.2gb], spins? [possibly], types [ext4]
[2017-01-10T00:54:37,184][INFO ][o.e.e.NodeEnvironment    ] [RcZpOgU] heap size [247.5mb], compressed ordinary object pointers [true]
[2017-01-10T00:54:37,187][INFO ][o.e.n.Node               ] node name [RcZpOgU] derived from node ID [RcZpOgUlTiiL5lZwkR-xMQ]; set [node.name] to override
[2017-01-10T00:54:37,190][INFO ][o.e.n.Node               ] version[5.1.1], pid[12], build[5395e21/2016-12-06T12:36:15.409Z], OS[Linux/4.4.21+/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_111-internal/25.111-b14]
[2017-01-10T00:54:38,767][INFO ][o.e.p.PluginsService     ] [RcZpOgU] loaded module [aggs-matrix-stats]
[2017-01-10T00:54:38,767][INFO ][o.e.p.PluginsService     ] [RcZpOgU] loaded module [ingest-common]
[2017-01-10T00:54:38,767][INFO ][o.e.p.PluginsService     ] [RcZpOgU] loaded module [lang-expression]
[2017-01-10T00:54:38,768][INFO ][o.e.p.PluginsService     ] [RcZpOgU] loaded module [lang-groovy]
[2017-01-10T00:54:38,768][INFO ][o.e.p.PluginsService     ] [RcZpOgU] loaded module [lang-mustache]
[2017-01-10T00:54:38,769][INFO ][o.e.p.PluginsService     ] [RcZpOgU] loaded module [lang-painless]
[2017-01-10T00:54:38,770][INFO ][o.e.p.PluginsService     ] [RcZpOgU] loaded module [percolator]
[2017-01-10T00:54:38,770][INFO ][o.e.p.PluginsService     ] [RcZpOgU] loaded module [reindex]
[2017-01-10T00:54:38,771][INFO ][o.e.p.PluginsService     ] [RcZpOgU] loaded module [transport-netty3]
[2017-01-10T00:54:38,771][INFO ][o.e.p.PluginsService     ] [RcZpOgU] loaded module [transport-netty4]
[2017-01-10T00:54:38,772][INFO ][o.e.p.PluginsService     ] [RcZpOgU] loaded plugin [discovery-kubernetes]
[2017-01-10T00:54:42,056][INFO ][o.e.n.Node               ] initialized
[2017-01-10T00:54:42,056][INFO ][o.e.n.Node               ] [RcZpOgU] starting ...
[2017-01-10T00:54:42,259][INFO ][o.e.t.TransportService   ] [RcZpOgU] publish_address {10.0.1.4:9300}, bound_addresses {10.0.1.4:9300}
[2017-01-10T00:54:42,266][INFO ][o.e.b.BootstrapCheck     ] [RcZpOgU] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[2017-01-10T00:54:46,226][INFO ][o.e.c.s.ClusterService   ] [RcZpOgU] new_master {RcZpOgU}{RcZpOgUlTiiL5lZwkR-xMQ}{rQ4LUwTeRxuiCLDm2vCwZw}{10.0.1.4}{10.0.1.4:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2017-01-10T00:54:46,247][INFO ][o.e.n.Node               ] [RcZpOgU] started
[2017-01-10T00:54:46,281][INFO ][o.e.g.GatewayService     ] [RcZpOgU] recovered [0] indices into cluster_state
[2017-01-10T00:55:22,164][INFO ][o.e.c.s.ClusterService   ] [RcZpOgU] added {{VKu2iLS}{VKu2iLSUSieopZbVc-2adg}{0JT2QBg5TMiRjRjwPRt06Q}{10.0.1.5}{10.0.1.5:9300},}, reason: zen-disco-node-join[{VKu2iLS}{VKu2iLSUSieopZbVc-2adg}{0JT2QBg5TMiRjRjwPRt06Q}{10.0.1.5}{10.0.1.5:9300}]
[2017-01-10T00:55:59,937][INFO ][o.e.c.s.ClusterService   ] [RcZpOgU] added {{WJNwRmB}{WJNwRmBrSYmRwWbIxIDrmw}{xZp7zxC1Q-et5xJt4bbniA}{10.0.2.4}{10.0.2.4:9300},}, reason: zen-disco-node-join[{WJNwRmB}{WJNwRmBrSYmRwWbIxIDrmw}{xZp7zxC1Q-et5xJt4bbniA}{10.0.2.4}{10.0.2.4:9300}]
```

So it works fine in Google cloud. I don't know what is the problem with Azure. Any help would be really appreciated.

**Comment by colemickens** [comment]
I'm subscribed to this issue. I don't know enough about this repo, ES, or what's going on to advise from the Azure side. AFAICT there's still no actionable logs here. The log message above indicates a problem with the logging infra, rather than a problem with ES or Azure.

**Comment by advishnuprasad** [comment]
@colemickens 
Please ignore that logging error. 

I am talking about the following error which I am not getting in GCS. Because of this error, elastic search master not finding the data/client nodes. I thought, it is specific to Azure, all works well with GCS. 
```
[2017-01-10T00:20:43,862][WARN ][i.f.e.d.k.KubernetesUnicastHostsProvider] [fMx0e_6] Exception caught during discovery: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
[2017-01-10T00:20:45,407][WARN ][i.f.e.d.k.KubernetesUnicastHostsProvider] [fMx0e_6] Exception caught during discovery: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
[2017-01-10T00:20:46,929][WARN ][i.f.e.d.k.KubernetesUnicastHostsProvider] [fMx0e_6] Exception caught during discovery: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
```

**Comment by colemickens** [comment]
Hm, it'd be great if we could get more information out of that. Can y'all let me know how these clusters were deployed? There's a small potential that this is a known issue affecting ACS/ACS-Engine, but it should not be affecting clusters deployed with Kubernetes-Anywhere.

Kind of a bummer that the logger logs that there was an error but includes no inner details...

**Comment by advishnuprasad** [comment]
Yes. Trying to get more from the debug log. But that lead into some other issue. I will wait for @pires reply. 

What we are trying achieve is this : https://github.com/pires/kubernetes-elasticsearch-cluster
I am trying to create ES cluster to scale up and down in ACS.

**Comment by colemickens** [comment]
In the meantime, how did you deploy the cluster?

**Comment by advishnuprasad** [comment]
I followed this https://docs.microsoft.com/en-us/azure/container-service/container-service-kubernetes-walkthrough

**Comment by colemickens** [comment]
So, we have a bug in ACS right now -- One of the certificates is generated such that it's missing a X509 Usage/ExtendedUsage attribute. This has caused problems with other non-Go clients, such as Python. We are rolling out a fix for it now. I can't guarantee it is the same root cause/fix, but I'm tentatively leaning towards it.

However, since this started out as an issue in the `kubernetes-anywhere` repo, I'm staying cautious about claiming we know the root problem. If @ejsmith can tell us the deployment method we might be able to be more confident.

**Comment by pires** [comment]
Also, I think I may have a change coming up that will no longer use the Kubernetes API but simply DNS. However, I'm glad this issue helped identify/validate a possible bug in ACS. Hat off to you!

**Comment by colemickens** [comment]
Yeah, we spotted it with Deis in December and staged the fix up. The logging from PyOpenSSL wasn't much better... I just got lucky and remembered this popping up in Slack once. Finally, an excuse for how much time I've spent in the Kube slack. 😄 

Also, if anyone is dying to use this asap, you can use the open source core of ACS, [ACS-Engine](https://github.com/Azure/acs-engine) which generates certificates differently and avoids this problem.

**Comment by pires** [comment]
@colemickens I am testing discovery based on DNS rather than the API but out of curiosity, and in case someone else asks around here, do you know when that fix will land in ACS?

**Comment by colemickens** [comment]
It's going to start rolling tomorrow, along with 1.5.1.

**Comment by colemickens** [comment]
It's going to start rolling tomorrow, along with 1.5.1 but it can take a week+ to do our full safe rollouts.

**Comment by ejsmith** [comment]
@colemickens do existing clusters automatically get updated when changes roll out? It seems like ACS just creates normal Azure resources for us. I didn't see anywhere in the docs where it talks about wether the cluster base OS / nodes will be managed for us or if we are responsible for their maintenance.

**Comment by ejsmith** [comment]
I updated my deployments to the new image and it works great!
