### ISSUE TITLE
Elasticsearch bug!! BindException: Address not available (after setting NETWORK_HOST)

### ISSUE THREAD

**Issue by BradErz** [pires/kubernetes-elasticsearch-cluster#96]
I was getting the error:

No up-and-running site-local (private) addresses found, got [name:lo (lo), name:eth0 (eth0)]

I saw in your troubleshooting section that this can be fixed by adding the environment variable NETWORK_HOST and setting it to eth0 (This is the correct interface name on the node of the kubernetes cluster.) However now i get another error stating that the Address is not available:

```
 braderz@Bradleys-MacBook-Pro  ~/Documents/projects/work  kubectl logs -f precise-buffalo-elasticsearch-master-2517039304-lvfxr
[2017-05-05T13:56:35,537][INFO ][o.e.n.Node               ] [precise-buffalo-elasticsearch-master-2517039304-lvfxr] initializing ...
[2017-05-05T13:56:35,667][INFO ][o.e.e.NodeEnvironment    ] [precise-buffalo-elasticsearch-master-2517039304-lvfxr] using [1] data paths, mounts [[/data (/dev/xvda1)]], net usable_space [14.3gb], net total_space [18.6gb], spins? [possibly], types [ext4]
[2017-05-05T13:56:35,668][INFO ][o.e.e.NodeEnvironment    ] [precise-buffalo-elasticsearch-master-2517039304-lvfxr] heap size [1007.3mb], compressed ordinary object pointers [true]
[2017-05-05T13:56:35,669][INFO ][o.e.n.Node               ] [precise-buffalo-elasticsearch-master-2517039304-lvfxr] node name [precise-buffalo-elasticsearch-master-2517039304-lvfxr], node ID [_EvFGAA7T0-X2qriKaXUNQ]
[2017-05-05T13:56:35,669][INFO ][o.e.n.Node               ] [precise-buffalo-elasticsearch-master-2517039304-lvfxr] version[5.3.0], pid[12], build[3adb13b/2017-03-23T03:31:50.652Z], OS[Linux/4.4.41-k8s/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_121/25.121-b13]
[2017-05-05T13:56:37,036][INFO ][o.e.p.PluginsService     ] [precise-buffalo-elasticsearch-master-2517039304-lvfxr] loaded module [aggs-matrix-stats]
[2017-05-05T13:56:37,036][INFO ][o.e.p.PluginsService     ] [precise-buffalo-elasticsearch-master-2517039304-lvfxr] loaded module [ingest-common]
[2017-05-05T13:56:37,036][INFO ][o.e.p.PluginsService     ] [precise-buffalo-elasticsearch-master-2517039304-lvfxr] loaded module [lang-expression]
[2017-05-05T13:56:37,036][INFO ][o.e.p.PluginsService     ] [precise-buffalo-elasticsearch-master-2517039304-lvfxr] loaded module [lang-groovy]
[2017-05-05T13:56:37,036][INFO ][o.e.p.PluginsService     ] [precise-buffalo-elasticsearch-master-2517039304-lvfxr] loaded module [lang-mustache]
[2017-05-05T13:56:37,036][INFO ][o.e.p.PluginsService     ] [precise-buffalo-elasticsearch-master-2517039304-lvfxr] loaded module [lang-painless]
[2017-05-05T13:56:37,036][INFO ][o.e.p.PluginsService     ] [precise-buffalo-elasticsearch-master-2517039304-lvfxr] loaded module [percolator]
[2017-05-05T13:56:37,036][INFO ][o.e.p.PluginsService     ] [precise-buffalo-elasticsearch-master-2517039304-lvfxr] loaded module [reindex]
[2017-05-05T13:56:37,037][INFO ][o.e.p.PluginsService     ] [precise-buffalo-elasticsearch-master-2517039304-lvfxr] loaded module [transport-netty3]
[2017-05-05T13:56:37,037][INFO ][o.e.p.PluginsService     ] [precise-buffalo-elasticsearch-master-2517039304-lvfxr] loaded module [transport-netty4]
[2017-05-05T13:56:37,038][INFO ][o.e.p.PluginsService     ] [precise-buffalo-elasticsearch-master-2517039304-lvfxr] no plugins loaded
[2017-05-05T13:56:40,067][INFO ][o.e.n.Node               ] [precise-buffalo-elasticsearch-master-2517039304-lvfxr] initialized
[2017-05-05T13:56:40,068][INFO ][o.e.n.Node               ] [precise-buffalo-elasticsearch-master-2517039304-lvfxr] starting ...
[2017-05-05T13:56:40,204][WARN ][i.n.u.i.MacAddressUtil   ] Failed to find a usable hardware address from the network interfaces; using random bytes: 2f:ab:ab:00:51:94:38:c8
[2017-05-05T13:56:40,418][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [precise-buffalo-elasticsearch-master-2517039304-lvfxr] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: BindTransportException[Failed to bind to [9300-9400]]; nested: BindException[Address not available];
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.3.0.jar:5.3.0]
Caused by: org.elasticsearch.transport.BindTransportException: Failed to bind to [9300-9400]
	at org.elasticsearch.transport.TcpTransport.bindToPort(TcpTransport.java:729) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.transport.TcpTransport.bindServer(TcpTransport.java:694) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.transport.netty4.Netty4Transport.doStart(Netty4Transport.java:183) ~[?:?]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:69) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.transport.TransportService.doStart(TransportService.java:196) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:69) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.node.Node.start(Node.java:610) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:287) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:370) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.0.jar:5.3.0]
	... 6 more
Caused by: java.net.BindException: Address not available
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:?]
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:127) ~[?:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:502) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:487) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980) ~[?:?]
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250) ~[?:?]
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:363) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

Any one have any ideas what is going wrong?

**Comment by pires** [comment]
It's an [Elasticsearch/Netty bug](https://discuss.elastic.co/t/es-5-2-0-in-kvm-netty-warning-failed-to-find-a-usable-hardware-address-from-the-network-interfaces/73717/2). Anyway, leaving it open for further reference.

**Comment by pires** [comment]
Btw, can you try with 5.3.2?

**Comment by BradErz** [comment]
Thanks for getting back to me, seems the same issue occurs with 5.3.2. Do you know when this was introduced? Any previous version I could use?

**Comment by pires** [comment]
Can you check the issue I linked in the my first comment?

**Comment by pires** [comment]
5.4.0 release seems to have fixed this following https://github.com/elastic/elasticsearch/pull/23540.

**Comment by Globegitter** [comment]
Hmm, I am running on 5.5.1 and having the exact same issue.

**Comment by pires** [comment]
The [Troubleshooting section](https://github.com/pires/kubernetes-elasticsearch-cluster#troubleshooting) has two entries that may help. If not, open a new issue and provide logs.

**Comment by Globegitter** [comment]
Ahh yes, changing `NETWORK_HOST` from `_eth0_` to `_eth0:ipv4_` did the trick.
